[package]
name = "f4se-plugin-rs"
version = "0.1.0"
authors = ["Elvyria <elvyria@tutanota.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
region = "3.0.0"

[build-dependencies]
bindgen = "0.63"
